---
# https://taskfile.dev
version: "3"

tasks:
  css:
    dir: ./internal
    desc: Build the assets
    cmds:
      - tailwindcss.exe -i ./assets/css/tailwind.css -o ./assets/css/input.css
  css-watch:
    dir: ./internal
    desc: Build the assets
    cmds:
      - tailwindcss.exe -i ./assets/css/tailwind.css -o ./assets/css/input.css --watch
  gen:
    desc: Generate templ templates
    cmds:
      - templ generate
  winres:
    desc: Make windows manifest for icon
    cmds:
      - go-winres make
  assets:
    desc: Build assets for project
    deps: [css, gen]
  run:
    desc: Run the application
    deps: [css, gen]
    env:
      TIMETRACKER_DEV: 1
    cmds:
      - go run .
  build:
    desc: Run the application
    deps: [css, gen, winres]
    cmds:
      - go build -ldflags "-w -s -H=windowsgui" .
  build-debug:
    desc: Run the application
    deps: [css, gen, winres]
    cmds:
      - go build -ldflags "-H=windowsgui" .
  release:
    desc: Tag commit and push to remote
    cmds:
      - git tag {{.CLI_ARGS}}
      - git push origin tag {{.CLI_ARGS}}
