---
# https://taskfile.dev
version: '3'

tasks:
  css:
    dir: ./internal
    desc: Build the assets
    cmds:
      - tailwindcss.exe -i ./assets/tailwind.css -o ./templates/tailwind.css
  css-watch:
    dir: ./internal
    desc: Build the assets
    cmds:
      - tailwindcss.exe -i ./assets/tailwind.css -o ./templates/tailwind.css --watch
  run:
    desc: Run the application
    cmds:
      - go run ./cmd/server/...
