---
# https://taskfile.dev
version: "3"

tasks:
  css:
    dir: ./internal
    desc: Build the assets
    cmds:
      - tailwindcss.exe -i ./assets/css/tailwind.css -o ./assets/css/input.css
  css-watch:
    dir: ./internal
    desc: Build the assets
    cmds:
      - tailwindcss.exe -i ./assets/css/tailwind.css -o ./assets/css/input.css --watch
  gen:
    desc: Generate templ templates
    cmds:
      - templ generate
  run:
    desc: Run the application
    deps: [css, gen]
    cmds:
      - go run .
  build:
    desc: Run the application
    deps: [css, gen]
    cmds:
      - go build -ldflags -H=windowsgui .
