---
# https://taskfile.dev
version: '3'

tasks:
  init:
    desc: Install some important commands and tools
    cmds:
      - npm install
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install github.com/vektra/mockery/v2@latest
      - go mod tidy
  assets:
    desc: Build the assets
    cmds:
      - tailwindcss.exe -i ./internal/assets/tailwind.css -o ./internal/assets/dist/tailwind.css
  run:
    desc: Run the application
    cmds:
      - go run ./cmd/server/...
